export const userConstants = {
  REGISTER_REQUEST: "USERS_REGISTER_REQUEST",
  REGISTER_SUCCESS: "USERS_REGISTER_SUCCESS",
  REGISTER_FAILURE: "USERS_REGISTER_FAILURE",

  LOGIN_REQUEST: "USERS_LOGIN_REQUEST",
  LOGIN_SUCCESS: "USERS_LOGIN_SUCCESS",
  LOGIN_FAILURE: "USERS_LOGIN_FAILURE",

  GUEST_SESSION: "USERS_GUEST_SESSION",
  GUEST_SESSION_FAILURE: "USERS_GUEST_SESSION_FAILURE",

  LOGOUT: "USERS_LOGOUT",

  TOGGLE_LOGIN_POPUP: "TOGGLE_LOGIN_POPUP",
};
